import React from 'react';
import { Row, Col } from 'react-bootstrap';
import Thinker from '../../../Libs/thinker.js';
/**
 * retweets and tweets charts in co-operative
 */
class TotalScore extends React.Component {
  componentDidMount() {
    Thinker.add_event('tweets_changed', (tweets) => {
      this.render();
    });
  }
  render() {
    
    let avg_like_count = 0;
    let avg_retweet_count = 0;
    let total_like_count = 0;
    let total_retweet_count = 0;
    const tweets = Thinker.getTweets();
    for(let i=0; i<tweets.length; i++){
      const tweet = tweets[i];
      const like_count = tweet.favorite_count;
      const retweet_count = tweet.retweet_count;
      total_like_count += like_count;
      total_retweet_count += retweet_count;
    }
    avg_like_count = total_like_count / tweets.length;
    avg_retweet_count = total_retweet_count / tweets.length;
    const score = parseInt(((avg_like_count * total_like_count) + 10 * (avg_retweet_count * total_retweet_count))/100);

    return (
      <Row>
        <Col md={12}>
          <h5><b>Total Score</b></h5>
          <p style={{ fontSize: 14 }}>User rating, depending on how much others are communicating with the content generated by the user. This rating is based on user's tweets and does not have a rating aspect.</p>
        </Col>
        <Col md={12} style={{marginBottom: 10}}>
          <Row>
            <Col md={4} sm={2}></Col>
            <Col md={4} sm={8} style={{border: 'solid', borderWidth: 4, borderRadius: 15, padding: 25}}>
              <h2 style={{textAlign: 'center'}}>{score}pt</h2>
            </Col>
          </Row>
        </Col>
      </Row>
    );
  }
}

export default TotalScore;
